config/routes.rb
Rails.application.routes.draw do
  
  resources :dashboard
  get 'welcome/index'
  get 'tasks/partner'
  devise_for :users
  resources :partner
  resources :users
  resources :tasks
  resources :comments

  root 'tasks#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :partnership
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of    :email,     :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  has_many :requests_sent, class_name: "Partnership", foreign_key: :friender_id, inverse_of: :friender
  has_many :requests_received, class_name: "Partnership", foreign_key: :friendee_id, inverse_of: :friendee
  has_many :comments
  has_many :tasks
  accepts_nested_attributes_for :tasks
  def partner
    User.where(id:self.matchee).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    # method to redirect a signed in user to the task index 
  def after_sign_in_path_for(user)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      super
    else
      stored_location_for(user) || request.referer || tasks_path
    end
  end

  def index
    @tasks = Task.all
    #assign an instance variable to the current user tasks so we can list these
    #on the tasks page for the user that is signed in
    @current_user_tasks = Task.where(user_id:current_user)
    @current_user_incomplete = @current_user_tasks.where(is_complete: false)
    @current_user_comments = Comment.where(user_id:current_user)
   
   #Need an inverse to get it to work on the partner page. 

    if current_user
      @current_partner = User.where(id:current_user.matchee).first
      # TODO This throws an error on sign up because there is no matched partner. 
      if @current_partner != nil
        @incomplete_partner_tasks = Task.where(user_id:@current_partner.id, is_complete: false)  
        @partner_tasks = Task.where(user_id:@current_partner.id, is_complete: false)
      end
      
      @current_user_comments_recieved = Comment.where(user_id:current_user.matchee)
      @comments = @current_user_comments + @current_user_comments_recieved
      @comments_sorted = @comments.sort_by &:created_at

      puts "======================"
      puts "current user id:"
      puts current_user.id
      puts "current matchee:"
      puts current_user.matchee


      puts "======================"
    

    #if your tasks are nil it throws up. Here's the fix:
      if @partner_tasks == nil
        @partner_tasks_incomplete = "You don't have any tasks!"
      else
        @partner_tasks_incomplete = @partner_tasks.where(is_complete: false)
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@comment = current_user.comments.new(comment_params)
    # @task.user_id = current_user.user_id if current_user
  	if @comment.save
  		redirect_to tasks_path
    else
       render "new"  
  	end
  end

  end

  def destroy
  end



 private
  def comment_params
      params.require(:comment).permit(
        :title, :username)
  end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def update
		@current_person = User.where(id: params[:id]).first
		if @current_person.is_matched == true
			update_matched = User.where(id: current_user.matchee).first
			update_matched.is_matched = false
		end
		@current_person.is_matched = true
		all_users = User.all
		prng = Random.new
		all_unmatched = all_users.where(is_matched: false || nil)

		# all_users[prng.rand(all_users.count)].id #need to have where is_match is not equal to true.
		rando_user = all_unmatched[prng.rand(all_unmatched.count)]
		if @current_person.id != rando_user.id
			@current_person.matchee = rando_user.id
			rando_user.matchee = @current_person.id
			if (@current_person.save && rando_user.save)
				redirect_to tasks_path
			else
				raise params.inspect
			end
		else
			raise params.inspect
		end 
	end
	# This only goes one way. I need to go two ways, having matchee being the inverse of matcher. 
	# SO: y is the other person to whom youre being matched. 
	# change y.matchee so that their id is equal to current_person. 
	# TODO: Fix:
	# Current user can be matched to themselves. 
	# User can ONLY be matched up to a user where rando_user.is_matched == nil || false.
	# Need a loop that will run the number of times of all_users.count to check for unmatched users. if I run through everyone randomly it won't necessarily hit everyone since some people could be hit twice. 
	# unmatched_users = Select all users where is_matchd == false || nil. 
	# make loop run for unmatched_users.count number of times. 

	#all unmatched users:
	#a random unmatched user:


end

app/controllers/partner_controller.rb
class PartnerController < ApplicationController
end

app/controllers/partnerships_controller.rb
class PartnershipsController < ApplicationController

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def edit
  end

  def new
    @task = Task.new
  end

  def create
  	@task = current_user.tasks.new(task_params)
    # @task.user_id = current_user.user_id if current_user
  	if @task.save
  		redirect_to tasks_path
    else
       render "new"  
  	end
  end

  def update
    task_update = Task.where(id: params[:id]).first
    task_update.is_complete = true
    if task_update.save
      redirect_to tasks_path
    else
      raise params.inspect
    end
    # puts "========================"
    # puts task_update.is_complete
    # puts "========================"
    # redirect_to tasks_path
  end

private
  def task_params
      params.require(:task).permit(
        :name, :user_id, :is_complete)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  	u = User.where(id: params[:id]).first
  	u.update(params.require(:user).permit(:id, :tasks_attributes => [:id, :is_complete]))
  	redirect_to tasks_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/partner_helper.rb
module PartnerHelper
end

app/helpers/partnerships_helper.rb
module PartnershipsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<head>
  <script src="http://d3js.org/d3.v3.min.js"></script>
</head>

<div class="all">
	<div class="container">
		<div class="left-col">
			<div class="menu">
				<h2 class="h2Title"><%= link_to "Follow Thru", tasks_path, :class => 'linked' %></h2>
				<hr />
				<p><%= link_to "Your Tasks", tasks_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Dashboard", dashboard_index_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'linked'%></p>
			</div>
		</div>
		<div class="main-col">
			<h1>DASHBOARD</h1>
			<div class="dashboard">
				<div class="stats">
				<h2>Stats</h2>

                  <script>

                      //<!--setting the calendar size-->
                      var width = 960,
                              height = 136,
                              cellSize = 17; // cell size

                      //setting the day format
                      var day = d3.time.format("%w"),
                              week = d3.time.format("%U"),
                              percent = d3.format(".1%"),
                              format = d3.time.format("%Y-%m-%d");

                      //setting the color
                      var color = d3.scale.quantize()
//                              .domain([0, 1])
                              .domain([-.05, .05])
                              .range(d3.range(11).map(function(d) { return "q" + d + "-11"; }));

                      //setting the svg window
                      var svg = d3.select("body").selectAll("svg")
                              .data(d3.range(2015, 2016))
                              .enter().append("svg")
                              .attr("width", width)
                              .attr("height", height)
                              .attr("class", "RdYlGn")
                              .append("g")
                              .attr("transform", "translate(" + ((width - cellSize * 53) / 2) + "," + (height - cellSize * 7 - 1) + ")");

                      //                      setting the year text
                      svg.append("text")
                              .attr("transform", "translate(-6," + cellSize * 3.5 + ")rotate(-90)")
                              .style("text-anchor", "middle")
                              .text(function(d) { return d; });



                      //                      formatting the day squares on the heat map
                      var rect = svg.selectAll(".day")
                              .data(function(d) { return d3.time.days(new Date(d, 0, 1), new Date(d + 1, 0, 1)); })
                              .enter().append("rect")
                              .attr("class", "day")
                              .attr("width", cellSize)
                              .attr("height", cellSize)
                              .attr("x", function(d) { return week(d) * cellSize; })
                              .attr("y", function(d) { return day(d) * cellSize; })
                              .attr("id", function(d){
                                  return d.id; //<-- Sets the ID
                              })
//                              .on("click", click)
                              .datum(format);

                                //working on click event- not working yet
//                              function click() {
//                                  if (d3.select(this).style({"opacity" = .9, "stroke"  = "grey"})){
//                                      (d3.select(this).style({"opacity" = 0, "stroke" = none})));
//                                  }
//                              }

//                      $("rect"[0]).change(MouseClick)
//                        function mouseClick(){
//                            var key = $(this)
//                                    .children(":selected")
//                                    .val();
//
//                            mouseClick({id : key});
//                        }


                      // formatting the month
                      svg.selectAll(".month")
                              .data(function(d) { return d3.time.months(new Date(d, 0, 1), new Date(d + 1, 0, 1)); })
                              .enter().append("path")
                              .attr("class", "month")
                              .attr("d", monthPath);
                                //mouseover event not functioning yet
//                              .on("mouseover", function(){
//                                  d3.selectAll(this).style("opcaity",.4);
//                              })
//                              .on("mouseout", mapMouseOut);




                      var dataset;
                      var taskData = [];
                      var lex = [];
                      var make_lex = function(td){
                          //fill lex with 365 0's
                          for(var z=0; z<365; z++){
                              lex[z] = 0;
                          }
                          //for all of the task data, which are day numbers
                          //add 1 to lex corresponding with that day number
                          $.each(td, function(datum){
                              lex[taskData[datum][0]] ++;
//                              console.log("Hi, I'm lex",lex);
                          });
                      };
                      //                      grabbing our JSON data
                      $.getJSON('/tasks.json',
                              function(data) {
                                  // the code inside this function will be run,
                                  // when the $.getJSON finishes retrieving the data
                                  dataset = data;
//                                  console.log(data);

                                  // selecting just the task objects
                                  var objies = data.tasks;
//                                  console.log("objies", objies);
//                                  var objies = $.each(data.tasks, function(){ //changed this from data.tasks to data
//                                      // changed this from console logging objies to data.tasks
//                                      console.log("objies", objies);
//                                      return objies;
//                                  });

//                                  selecting the task updated_at times
                                  $.each(objies, function(i){
                                      updateTimes = objies[i].updated_at.substring(0,10);
//                                      console.log("update times", updateTimes);
//                                      testing datetoflo function
//                                      console.log("we are taking in and returning",updateTimes, dateToFlo(updateTimes));
                                      taskData.push([dateToFlo(updateTimes)]);
                                  });
                                  make_lex(taskData);
//                                  console.log("lex lex lex", lex);

                                  // this takes fills the day squares with the correct shade of green
                                  // based on accomplished tasks
                                  for (var l = 0; l< rect[0].length; l++){
                                      if(lex[l] == 0)
                                          document.getElementsByTagName(rect[0][l].style.fill = "#eee");
                                      //                          console.log(rect[0][l]);
                                      else if (lex[l] <= 2)
                                          document.getElementsByTagName(rect[0][l].style.fill = "#d6e685");
                                      else if (lex[l] <= 4)
                                          document.getElementsByTagName(rect[0][l].style.fill = "#8cc665");
                                      else if (lex[l] <= 7)
                                          document.getElementsByTagName(rect[0][l].style.fill = "#44a340");
                                      else
                                          document.getElementsByTagName(rect[0][l].style.fill = "#1e6823");

                                  }
                              });
                      //
                      //                      //this takes in the updated_at date and converts it to the day number
                      function dateToFlo (taskDate){
                          var dateNum;
                          var offsets = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
                          dateNum = parseInt(taskDate.substring(8,10)) + offsets[parseInt(taskDate.substring(5,7) - 1)];

                          // if (taskDate.substring(5,7) == "01"){
                          // }
                          // else if (taskDate.substring(5,7) == "02"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 31;
                          // }
                          // else if (taskDate.substring(5,7) == "03"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 59;
                          // }
                          // else if (taskDate.substring(5,7) == "04"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 90;
                          // }
                          // else if (taskDate.substring(5,7) == "05"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 120;
                          // }
                          // else if (taskDate.substring(5,7) == "06"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 151;
                          // }
                          // else if (taskDate.substring(5,7) == "07"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 181;
                          // }
                          // else if (taskDate.substring(5,7) == "08"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 212;
                          // }
                          // else if (taskDate.substring(5,7) == "09"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 243;
                          // }
                          // else if (taskDate.substring(5,7) == "10"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 273;
                          // }
                          // else if (taskDate.substring(5,7) == "11"){
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 304;
                          // }
                          // else{
                          //     dateNum = parseInt(taskDate.substring(8,10)) + 334;
                          // }
                          return dateNum;
                      }



                      // formatting the month lines
                      function monthPath(t0) {
                          var t1 = new Date(t0.getFullYear(), t0.getMonth() + 1, 0),
                                  d0 = +day(t0), w0 = +week(t0),
                                  d1 = +day(t1), w1 = +week(t1);
                          return "M" + (w0 + 1) * cellSize + "," + d0 * cellSize
                                  + "H" + w0 * cellSize + "V" + 7 * cellSize
                                  + "H" + w1 * cellSize + "V" + (d1 + 1) * cellSize
                                  + "H" + (w1 + 1) * cellSize + "V" + 0
                                  + "H" + (w0 + 1) * cellSize + "Z";
                      }

                      d3.select(self.frameElement).style("height", "2910px");
                  </script>

				</div>
				<div class="profile">
					<h2>Profile</h2>
						<b><p><%= link_to 'Edit profile', edit_user_registration_path, :class => 'boxLink' %> </p></b>
						<% if current_user.matchee == nil %>
							<b><%= link_to 'Match up with another user', dashboard_path(current_user.id), method: :patch, :class => 'boxLink' %>
						<% else %>
							<%= link_to "You're already matched up, but clicking this will match you up with another user", dashboard_path(current_user.id), method: :patch, :class => 'boxLink' %></b>
						<% end %>
				</div>


			</div>
  	</div>
	</div>
</div>

app/views/partner/index.html.erb
<div class="all">
	<div class="container">
		<div class="left-col">
			<div class="menu">
				<h2 class="h2Title"><%= link_to "Follow Thru", tasks_path, :class => 'linked' %></h2>
				<hr />
				<p><%= link_to "Your Tasks", tasks_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Dashboard", dashboard_index_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'linked'%></p>
			</div>
		</div>
		<div class="main-col">
			<div class="switcher">
				<div class="inactiveSwitch" class="">
					<p><%= link_to "Your Tasks", tasks_path, :class => "linker" %></p>
				</div>
				<div class="activeSwitch">
					<p><%= link_to "Your Partner's Tasks", tasks_partner_path, :class => 'linker' %></p>
				</div>
			</div>
			<br><br>
			<div class="tasks">
				<%# if @incomplete_partner_tasks == nil %>
				<%# else %>
				<% if @current_partner == nil %>
					<b><%= link_to 'Match up with another user!', dashboard_path(current_user.id), method: :patch, :class => 'boxLink' %>
						
				<% else %>
					<% @partner_tasks.each do |t| %>
					<div class="notDoneTask">
						<div class="deleter">
							<span class='xButton'>&nbsp&nbsp<%#= link_to "X", task_path(t.id), method: :patch %>&nbsp&nbsp&nbsp&nbsp</span>
						</div>
						<span class="taskText"><%= t.name %></span>
					</div>
					<hr />
					<% end %>
				<% end %>

<!-- 			<%#= form_for current_user do |f| %>
				<%#= f.fields_for :tasks do |builder| %>
				<%# if builder.object.is_complete == false %>
					<div class="notDoneTask">
					<div class="deleter">
						<span class='xButton'>&nbsp&nbsp<%#= link_to "X", task_path(builder.object.id), method: :patch %>&nbsp&nbsp&nbsp&nbsp</span>
					</div>
						<span class="taskText">
							<%# if builder.object.is_complete == false %>
								<%#= builder.object.name %>
							<%# end %>
						</span>
					</div>
 -->
					
					<%# end %>
					<%#= builder.check_box :is_complete%>
				<%# end %>
			<%#= f.submit %>
			<%# end %>
        <tr>
        </tr>
        <tr>
        	<td><%#= render 'form' %></td>
        </tr>
        <%# if @comments == nil %>
        <%# else %>
        <td><%= render 'tasks/comment' %></td>
        <%# @comments.each do |c| %>
        	<%#= c.title %>
        	<%#= c.user.email %>
        <%# end %>	
        <%# end %>

      
    	</div>
		</div>
	</div>
</div>


<script>
	// Switch between User and Partners tasks. 
	// $('.inactiveSwitch').click(function() {
	// 	var $this = $(this);
	// 	if(!$this.hasClass('inactiveSwitch'))
	// 		$('.inactiveSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$('.activeSwitch').toggleClass('activeSwitch').toggleClass("inactiveSwitch");
	// 		$this.toggleClass("inactiveSwitch").toggleClass("activeSwitch");
	// });
	// $('.activeSwitch').click(function() {
	// 	var $this = $(this);
	// 	if(!$this.hasClass('inactiveSwitch'))
	// 		$('.inactiveSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$('.activeSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$this.toggleClass("activeSwitch").toggleClass("inactiveSwitch");
	// });
	// Switch between task done and not done.
	// make the delete button appear
	// $('.notDoneTask').click(function(){
	// 	$(this).toggleClass('doneTask').toggleClass('notDoneTask');
	// 	if($(this).hasClass('doneTask')){
	// 		// $('.deleter').show();
	// 	}
	// })

// </script>


<%#= link_to 'Edit your to do list', edit_list_path(task) %>

app/views/tasks/_index.html.erb
<div class="all">
	<div class="container">
		<div class="left-col">
			<div class="menu">
				<h2 class="h2Title"><%= link_to "Follow Thru", tasks_path, :class => 'linked' %></h2>
				<hr />
				<p><%= link_to "Your Tasks", tasks_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Dashboard", dashboard_index_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'linked'%></p>
			</div>
		</div>
		<div class="main-col">
			<div class="switcher">
				<div class="activeSwitch" class="">
					<p><%= link_to "Your Tasks", tasks_path, :class => "linker" %></p>
				</div>
				<div class="inactiveSwitch">
					<p><%= link_to "Your Partner's Tasks", partner_index_path, :class => 'linker' %></p>
				</div>
			</div>
			<br><br>
			<div class="tasks">
				<%# if @current_user_incomplete == nil %>
				<%# else %>
				<% @current_user_incomplete.each do |t| %>
				<div class="notDoneTask">
					<div class="deleter">
						<span class='xButton'>&nbsp&nbsp<%= link_to "X", task_path(t.id), method: :patch %>&nbsp&nbsp&nbsp&nbsp</span>
					</div>
					<span class="taskText"><%= t.name %></span>

					<hr>
				</div>

				<%# end %>
				<% end %>

<!-- 			<%#= form_for current_user do |f| %>
				<%#= f.fields_for :tasks do |builder| %>
				<%# if builder.object.is_complete == false %>
					<div class="notDoneTask">
					<div class="deleter">
						<span class='xButton'>&nbsp&nbsp<%#= link_to "X", task_path(builder.object.id), method: :patch %>&nbsp&nbsp&nbsp&nbsp</span>
					</div>
						<span class="taskText">
							<%# if builder.object.is_complete == false %>
								<%#= builder.object.name %>
							<%# end %>
						</span>
					</div>
 -->
					<%# end %>
					<%#= builder.check_box :is_complete%>
				<%# end %>
			<%#= f.submit %>
			<%# end %>
        <tr>
        </tr>
        <tr>
        	<div class="formClass">
        	<td><%= render 'form' %></td>
        	</div>
        </tr>
      		
        	
      	<td><%= render 'comment' %></td>
    	</div>
		</div>
	</div>
</div>

	
<script>
	// Switch between User and Partners tasks. 
	// $('.inactiveSwitch').click(function() {
	// 	var $this = $(this);
	// 	if(!$this.hasClass('inactiveSwitch'))
	// 		$('.inactiveSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$('.activeSwitch').toggleClass('activeSwitch').toggleClass("inactiveSwitch");
	// 		$this.toggleClass("inactiveSwitch").toggleClass("activeSwitch");
	// });
	// $('.activeSwitch').click(function() {
	// 	var $this = $(this);
	// 	if(!$this.hasClass('inactiveSwitch'))
	// 		$('.inactiveSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$('.activeSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$this.toggleClass("activeSwitch").toggleClass("inactiveSwitch");
	// });
	// Switch between task done and not done.
	// make the delete button appear
	$('.notDoneTask').click(function(){
		$(this).toggleClass('doneTask').toggleClass('notDoneTask');
		if($(this).hasClass('doneTask')){
			// $('.deleter').show();
		}
	})

// </script>


<%#= link_to 'Edit your to do list', edit_list_path(task) %>

app/views/tasks/_partner_tasks.html.erb
<%= form_for partner do |f| %>
	<%= f.fields_for :tasks do |task| %>
		<div class="notDoneTask">
			<div class="deleter">
				<span class='xButton'>&nbsp&nbsp
				<%= link_to "X", task_path(task.object.id), method: :patch %>&nbsp&nbsp&nbsp&nbsp
				</span>
			</div>
			<span class="taskText">
				<%= task.object.name %>
			</span>
		</div>
		<hr>
		<% end %>
		<% end %>
		</hr>

app/views/tasks/partner.html.erb
<div class="all">
	<div class="container">
		<div class="left-col">
			<div class="menu">
				<h2 class="h2Title"><%= link_to "Follow Thru", tasks_path, :class => 'linked' %></h2>
				<hr />
				<p><%= link_to "Your Tasks", tasks_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Dashboard", dashboard_index_path, :class => 'linked' %></p>
				<hr />
				<p><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'linked'%></p>
			</div>
		</div>
		<div class="main-col">
			<div class="switcher">
				<div class="inactiveSwitch" class="">
					<p><%= link_to "Your Tasks", tasks_path, :class => "linker" %></p>
				</div>
				<div class="activeSwitch">
					<p><%= link_to "Your Partner's Tasks", tasks_partner_path, :class => 'linker' %></p>
				</div>
			</div>
			<br><br>
			<div class="tasks">
				<% if @partner_tasks_incomplete == nil %>
				<% else %>
				<% @partner_tasks_incomplete.each do |t| %>
				<div class="notDoneTask">
					<div class="deleter">
						<span class='xButton'>&nbsp&nbsp<%= link_to "X", task_path(t.id), method: :patch %>&nbsp&nbsp&nbsp&nbsp</span>
					</div>
					<span class="taskText"><%= t.name %></span>
				</div>

				<% end %>
				<% end %>

<!-- 			<%#= form_for current_user do |f| %>
				<%#= f.fields_for :tasks do |builder| %>
				<%# if builder.object.is_complete == false %>
					<div class="notDoneTask">
					<div class="deleter">
						<span class='xButton'>&nbsp&nbsp<%#= link_to "X", task_path(builder.object.id), method: :patch %>&nbsp&nbsp&nbsp&nbsp</span>
					</div>
						<span class="taskText">
							<%# if builder.object.is_complete == false %>
								<%#= builder.object.name %>
							<%# end %>
						</span>
					</div>
 -->
					<hr>
					<%# end %>
					<%#= builder.check_box :is_complete%>
				<%# end %>
			<%#= f.submit %>
			<%# end %>
        <tr>
        </tr>
        <tr>
        	<td><%#= render 'form' %></td>
        </tr>
        <% if @comments == nil %>
        <% else %>
        <% @comments.each do |c| %>
        	<%= c.title %>
        	<%= c.user.email %>
        <% end %>	
        <% end %>

      
    	</div>
		</div>
	</div>
</div>


<script>
	// Switch between User and Partners tasks. 
	// $('.inactiveSwitch').click(function() {
	// 	var $this = $(this);
	// 	if(!$this.hasClass('inactiveSwitch'))
	// 		$('.inactiveSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$('.activeSwitch').toggleClass('activeSwitch').toggleClass("inactiveSwitch");
	// 		$this.toggleClass("inactiveSwitch").toggleClass("activeSwitch");
	// });
	// $('.activeSwitch').click(function() {
	// 	var $this = $(this);
	// 	if(!$this.hasClass('inactiveSwitch'))
	// 		$('.inactiveSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$('.activeSwitch').toggleClass('inactiveSwitch').toggleClass("activeSwitch");
	// 		$this.toggleClass("activeSwitch").toggleClass("inactiveSwitch");
	// });
	// Switch between task done and not done.
	// make the delete button appear
	$('.notDoneTask').click(function(){
		$(this).toggleClass('doneTask').toggleClass('notDoneTask');
		if($(this).hasClass('doneTask')){
			// $('.deleter').show();
		}
	})

// </script>


<%#= link_to 'Edit your to do list', edit_list_path(task) %>